import Head from "next/head";
import "../styles/globals.css";
import Script from "next/script";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>CNN</title>
        <meta
          name="facebook-domain-verification"
          content="wifrayncgdy8y2x7qp63zmu95p6wp2"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <Script strategy="lazyOnload">
  {!function(f,b,e,v,n,t,s) {
  if(f.fbq) return;
  n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}
  // (window, document,'script',
  // 'https://connect.facebook.net/en_US/fbevents.js')
  // fbq('init', '1379713562514600');
  // fbq('track', 'PageView')}
</Script> */}

        <noscript
          dangerouslySetInnerHTML={{
            __html: `
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1379713562514600&ev=PageView&noscript=1"
          />
          `,
          }}
        ></noscript>
      </Head>
      <Script id="facebook-pixel">
        {` !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '1379713562514600');
  fbq('track', 'PageView');`}
      </Script>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
