import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";

const Home = () => {
  useEffect(() => {
    Router.push({
      pathname: "cnn-academy/en",
    });
  }, []);
  return (
    <div>
      <Head>
        <title>CNN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
